DROP DATABASE IF EXISTS bottomlessbox;
CREATE DATABASE bottomlessbox;
USE bottomlessbox;

CREATE TABLE users (
    id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(30),
    password VARCHAR(30)
);

CREATE TABLE pockets (
	id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(30),
    taxable BOOLEAN
);

CREATE TABLE items (
	id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(30),
    price DECIMAL(10),
    quantity DECIMAL(10),
    pocket_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_pocket FOREIGN KEY (pocket_id) REFERENCES pockets(id) ON DELETE CASCADE
);